function Get-LearningContent-centos {
    $fs = @{
        Type = 'dir'
        Owner = 'root'
        Group = 'root'
        Children = @{
            'etc' = @{
                Type = 'dir'
                Owner = 'root'
                Group = 'root'
                Children = @{
                    'os_release' = @{
                        Type = 'file'; Owner = 'root'; Group = 'root'
                        Content = @(
                            'NAME="Rocky Linux"',
                            'VERSION="9.4 (Blue Onyx)"',
                            'ID="rocky"',
                            'ID_LIKE="rhel centos fedora"',
                            'VERSION_ID="9.4"',
                            'PLATFORM_ID="platform:el9"',
                            'PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"',
                            'ANSI_COLOR="0;32"',
                            'CPE_NAME="cpe:/o:rocky:rocky:9::baseos"',
                            'HOME_URL="https://rockylinux.org/"',
                            'DOCUMENTATION_URL="https://docs.rockylinux.org/"',
                            'SUPPORT_END="2032-05-31"'
                        )
                    }
                    'hostname' = @{
                        Type = 'file'; Owner = 'root'; Group = 'root'
                        Content = @('rocky-box')
                    }
                    'resolv_conf' = @{
                        Type = 'file'; Owner = 'root'; Group = 'root'
                        Content = @(
                            '# Generated by NetworkManager',
                            'search localdomain',
                            'nameserver 192.168.1.1',
                            'nameserver 1.1.1.1'
                        )
                    }
                    'selinux' = @{
                        Type = 'dir'; Owner = 'root'; Group = 'root'
                        Children = @{
                            'config' = @{
                                Type = 'file'; Owner = 'root'; Group = 'root'
                                Content = @(
                                    '# This file controls the state of SELinux on the system.',
                                    'SELINUX=enforcing',
                                    'SELINUXTYPE=targeted'
                                )
                            }
                        }
                    }
                    'yum_repos_d' = @{
                        Type = 'dir'; Owner = 'root'; Group = 'root'
                        Children = @{
                            'rocky_repo' = @{
                                Type = 'file'; Owner = 'root'; Group = 'root'
                                Content = @(
                                    '[rocky-baseos]',
                                    'name=Rocky Linux $releasever - BaseOS',
                                    'mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=BaseOS-$releasever',
                                    'enabled=1',
                                    'gpgcheck=1',
                                    'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial',
                                    '',
                                    '[rocky-appstream]',
                                    'name=Rocky Linux $releasever - AppStream',
                                    'mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=AppStream-$releasever',
                                    'enabled=1',
                                    'gpgcheck=1',
                                    'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial',
                                    '',
                                    '[rocky-extras]',
                                    'name=Rocky Linux $releasever - Extras',
                                    'mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=Extras-$releasever',
                                    'enabled=1',
                                    'gpgcheck=1',
                                    'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial'
                                )
                            }
                        }
                    }
                    'firewalld' = @{
                        Type = 'dir'; Owner = 'root'; Group = 'root'
                        Children = @{
                            'firewalld_conf' = @{
                                Type = 'file'; Owner = 'root'; Group = 'root'
                                Content = @(
                                    '# firewalld config',
                                    'DefaultZone=public',
                                    'MinimalMark=100',
                                    'CleanUpOnExit=yes',
                                    'Lockdown=no',
                                    'IPv6_rpfilter=yes'
                                )
                            }
                            'zones' = @{
                                Type = 'dir'; Owner = 'root'; Group = 'root'
                                Children = @{
                                    'public_xml' = @{
                                        Type = 'file'; Owner = 'root'; Group = 'root'
                                        Content = @(
                                            '<?xml version="1.0" encoding="utf-8"?>',
                                            '<zone>',
                                            '  <short>Public</short>',
                                            '  <description>For use in public areas.</description>',
                                            '  <service name="ssh"/>',
                                            '  <service name="dhcpv6-client"/>',
                                            '  <service name="cockpit"/>',
                                            '</zone>'
                                        )
                                    }
                                }
                            }
                        }
                    }
                    'NetworkManager' = @{
                        Type = 'dir'; Owner = 'root'; Group = 'root'
                        Children = @{
                            'NetworkManager_conf' = @{
                                Type = 'file'; Owner = 'root'; Group = 'root'
                                Content = @(
                                    '[main]',
                                    'plugins=keyfile',
                                    'dhcp=internal',
                                    '',
                                    '[logging]',
                                    'level=INFO',
                                    'domains=ALL',
                                    '',
                                    '[connectivity]',
                                    'interval=300'
                                )
                            }
                            'system-connections' = @{
                                Type = 'dir'; Owner = 'root'; Group = 'root'
                                Children = @{
                                    'eth0_nmconnection' = @{
                                        Type = 'file'; Owner = 'root'; Group = 'root'
                                        Content = @(
                                            '[connection]',
                                            'id=eth0',
                                            'type=ethernet',
                                            'interface-name=eth0',
                                            'autoconnect=true',
                                            '',
                                            '[ipv4]',
                                            'method=auto',
                                            'dns=1.1.1.1;8.8.8.8;',
                                            '',
                                            '[ipv6]',
                                            'method=auto'
                                        )
                                    }
                                }
                            }
                        }
                    }
                    'ssh' = @{
                        Type = 'dir'; Owner = 'root'; Group = 'root'
                        Children = @{
                            'sshd_config_d' = @{
                                Type = 'dir'; Owner = 'root'; Group = 'root'
                                Children = @{
                                    '50-redhat_conf' = @{
                                        Type = 'file'; Owner = 'root'; Group = 'root'
                                        Content = @(
                                            '# RHEL-family SSH defaults',
                                            'PasswordAuthentication yes',
                                            'ChallengeResponseAuthentication no',
                                            'UsePAM yes',
                                            'X11Forwarding yes',
                                            'PrintMotd no'
                                        )
                                    }
                                }
                            }
                        }
                    }
                    'cron_d' = @{
                        Type = 'dir'; Owner = 'root'; Group = 'root'
                        Children = @{
                            '0hourly' = @{
                                Type = 'file'; Owner = 'root'; Group = 'root'
                                Content = @(
                                    '# Run the hourly jobs',
                                    '01 * * * * root run-parts /etc/cron.hourly'
                                )
                            }
                            'sysstat' = @{
                                Type = 'file'; Owner = 'root'; Group = 'root'
                                Content = @(
                                    '# System activity reporting',
                                    '*/10 * * * * root /usr/lib64/sa/sa1 1 1'
                                )
                            }
                        }
                    }
                    'pki' = @{
                        Type = 'dir'; Owner = 'root'; Group = 'root'
                        Children = @{
                            'rpm-gpg' = @{
                                Type = 'dir'; Owner = 'root'; Group = 'root'
                                Children = @{
                                    'RPM-GPG-KEY-rockyofficial' = @{
                                        Type = 'file'; Owner = 'root'; Group = 'root'
                                        Content = @(
                                            '-----BEGIN PGP PUBLIC KEY BLOCK-----',
                                            'mQINBG... (Rocky Linux official signing key)',
                                            '-----END PGP PUBLIC KEY BLOCK-----'
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
            }
            'var' = @{
                Type = 'dir'; Owner = 'root'; Group = 'root'
                Children = @{
                    'log' = @{
                        Type = 'dir'; Owner = 'root'; Group = 'root'
                        Children = @{
                            'messages' = @{
                                Type = 'file'; Owner = 'root'; Group = 'root'
                                Content = @(
                                    'Jun  1 08:15:01 rocky-box rsyslogd: [origin software="rsyslogd"] start',
                                    'Jun  1 08:15:02 rocky-box kernel: SELinux:  Initializing.',
                                    'Jun  1 08:15:02 rocky-box kernel: SELinux: 2048 avtab hash slots, 112345 rules',
                                    'Jun  1 08:15:02 rocky-box kernel: SELinux:  enforcing mode enabled',
                                    'Jun  1 08:15:03 rocky-box systemd[1]: Starting Journal Service...',
                                    'Jun  1 08:15:03 rocky-box systemd[1]: Started Journal Service.',
                                    'Jun  1 08:15:04 rocky-box systemd[1]: Starting firewalld...',
                                    'Jun  1 08:15:04 rocky-box systemd[1]: Started firewalld.',
                                    'Jun  1 08:15:05 rocky-box NetworkManager[1024]: started (version 1.48.0)',
                                    'Jun  1 08:15:06 rocky-box sshd[1120]: Server listening on 0.0.0.0 port 22.',
                                    'Jun  1 08:15:10 rocky-box auditd[1056]: Audit daemon started',
                                    'Jun  1 08:30:01 rocky-box CROND[1201]: (root) CMD (run-parts /etc/cron.hourly)',
                                    'Jun  1 08:45:22 rocky-box sshd[1250]: Accepted publickey for student from 192.168.1.100',
                                    'Jun  1 08:45:22 rocky-box sshd[1250]: pam_unix(sshd:session): session opened for user student',
                                    'Jun  1 09:00:01 rocky-box CROND[1300]: (root) CMD (/usr/lib64/sa/sa1 1 1)',
                                    'Jun  1 09:15:01 rocky-box rsyslogd: rsyslogd was HUPed'
                                )
                            }
                            'audit' = @{
                                Type = 'dir'; Owner = 'root'; Group = 'root'
                                Children = @{
                                    'audit_log' = @{
                                        Type = 'file'; Owner = 'root'; Group = 'root'
                                        Content = @(
                                            'type=DAEMON_START msg=audit(1717229702.123:1): auditd start, ver=3.1.2',
                                            'type=SYSTEMD_BOOT msg=audit(1717229702.456:2): boot_id=7a8b3c2d1e4f',
                                            'type=USER_LOGIN msg=audit(1717231522.789:345): pid=1250 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0 msg=''op=login id=1000 exe="/usr/sbin/sshd" hostname=192.168.1.100 addr=192.168.1.100 terminal=ssh res=success''',
                                            'type=AVC msg=audit(1717231800.001:500): avc: denied { read } for pid=1500 comm="httpd" name="index.html" dev=sda2 ino=12345 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:admin_home_t:s0 tclass=file permissive=0'
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
            }
            'boot' = @{
                Type = 'dir'; Owner = 'root'; Group = 'root'
                Children = @{
                    'grub2' = @{
                        Type = 'dir'; Owner = 'root'; Group = 'root'
                        Children = @{
                            'grub_cfg' = @{
                                Type = 'file'; Owner = 'root'; Group = 'root'
                                Content = @(
                                    '# GRUB2 config generated by grub2-mkconfig',
                                    'set default="0"',
                                    'set timeout=5',
                                    '',
                                    'menuentry "Rocky Linux (5.14.0-427.el9.x86_64) 9.4" {',
                                    '  linux /vmlinuz-5.14.0-427.el9.x86_64 root=/dev/mapper/rl-root ro crashkernel=auto',
                                    '  initrd /initramfs-5.14.0-427.el9.x86_64.img',
                                    '}'
                                )
                            }
                        }
                    }
                    'vmlinuz-5.14.0-427.el9.x86_64' = @{
                        Type = 'file'; Owner = 'root'; Group = 'root'
                        Content = @('[kernel image - 6.5 MB]')
                    }
                    'initramfs-5.14.0-427.el9.x86_64.img' = @{
                        Type = 'file'; Owner = 'root'; Group = 'root'
                        Content = @('[initramfs image - 32 MB]')
                    }
                }
            }
            'home' = @{
                Type = 'dir'; Owner = 'root'; Group = 'root'
                Children = @{
                    'student' = @{
                        Type = 'dir'; Owner = 'student'; Group = 'student'
                        Children = @{
                            'documents' = @{
                                Type = 'dir'; Owner = 'student'; Group = 'student'
                                Children = @{
                                    'notes_txt' = @{
                                        Type = 'file'; Owner = 'student'; Group = 'student'
                                        Content = @(
                                            '# Rocky Linux Learning Notes',
                                            'SELinux contexts and booleans',
                                            'Firewalld zone management',
                                            'Systemd service hardening',
                                            'DNF module streams',
                                            'Kernel Live Patching'
                                        )
                                    }
                                    'todo_txt' = @{
                                        Type = 'file'; Owner = 'student'; Group = 'student'
                                        Content = @(
                                            '1. Configure SELinux for httpd',
                                            '2. Set up firewalld zones',
                                            '3. Enable cockpit service',
                                            '4. Practice dnf history rollback'
                                        )
                                    }
                                }
                            }
                            'bashrc' = @{
                                Type = 'file'; Owner = 'student'; Group = 'student'
                                Content = @(
                                    '# .bashrc',
                                    'export PS1="[\u@\h \W]\\$ "',
                                    'alias ll="ls -l"',
                                    'alias lh="ls -lh"',
                                    'alias la="ls -la"',
                                    'alias grep="grep --color=auto"',
                                    'alias df="df -h"'
                                )
                            }
                        }
                    }
                }
            }
        }
    }

    $tasks = @(
        @{ Id = 1; Title = 'List directory contents'; Difficulty = 'beginner'
            ExpectedCommand = 'ls /home/student'
            Description = @('Use ls to list files and directories inside /home/student.', 'Look for the documents folder and bashrc file.')
            Hint = 'Try: ls /home/student' }
        @{ Id = 2; Title = 'Navigate to documents'; Difficulty = 'beginner'
            ExpectedCommand = 'cd /home/student/documents'
            Description = @('Change directory to /home/student/documents and verify with pwd.')
            Hint = 'Use cd followed by the full path' }
        @{ Id = 3; Title = 'Check OS release info'; Difficulty = 'beginner'
            ExpectedCommand = 'cat /etc/os-release'
            Description = @('Display /etc/os-release to see which Rocky Linux version is installed.')
            Hint = 'cat /etc/os-release' }
        @{ Id = 4; Title = 'Create a lab directory'; Difficulty = 'beginner'
            ExpectedCommand = 'mkdir /home/student/lab-files'
            Description = @('Create a new directory called lab-files under /home/student.')
            Hint = 'mkdir <path>' }
        @{ Id = 5; Title = 'Read system hostname'; Difficulty = 'beginner'
            ExpectedCommand = 'cat /etc/hostname'
            Description = @('Display the hostname stored in /etc/hostname.')
            Hint = 'cat /etc/hostname' }
        @{ Id = 6; Title = 'List installed packages'; Difficulty = 'intermediate'
            ExpectedCommand = 'dnf list installed 2>/dev/null | head -20'
            Description = @('Use dnf to list installed packages. Pipe through head to see 20 lines.')
            Hint = 'dnf list installed | head -20' }
        @{ Id = 7; Title = 'Search for httpd package'; Difficulty = 'intermediate'
            ExpectedCommand = 'dnf search httpd'
            Description = @('Search DNF repositories for the Apache HTTP server package (httpd).')
            Hint = 'dnf search <term>' }
        @{ Id = 8; Title = 'Find SSH log entries'; Difficulty = 'intermediate'
            ExpectedCommand = 'grep sshd /var/log/messages'
            Description = @('Search /var/log/messages for lines containing sshd.')
            Hint = 'grep <pattern> <file>' }
        @{ Id = 9; Title = 'Check SELinux mode'; Difficulty = 'intermediate'
            ExpectedCommand = 'getenforce'
            Description = @('Run getenforce to check if SELinux is enforcing, permissive, or disabled.')
            Hint = 'getenforce' }
        @{ Id = 10; Title = 'Check disk space'; Difficulty = 'intermediate'
            ExpectedCommand = 'df -h'
            Description = @('Use df -h to display disk usage in human-readable format.')
            Hint = 'df -h' }
        @{ Id = 11; Title = 'Restart httpd service'; Difficulty = 'advanced'
            ExpectedCommand = 'systemctl restart httpd'
            Description = @('Use systemctl to restart the httpd service.')
            Hint = 'systemctl restart <service>' }
        @{ Id = 12; Title = 'View journal logs'; Difficulty = 'advanced'
            ExpectedCommand = 'journalctl -n 20'
            Description = @('View the 20 most recent entries from the systemd journal.')
            Hint = 'journalctl -n <number>' }
        @{ Id = 13; Title = 'List firewall rules'; Difficulty = 'advanced'
            ExpectedCommand = 'firewall-cmd --list-all'
            Description = @('Use firewall-cmd to list all configured firewall rules.')
            Hint = 'firewall-cmd --list-all' }
        @{ Id = 14; Title = 'Find config files'; Difficulty = 'advanced'
            ExpectedCommand = 'find /etc -name "*.conf" 2>/dev/null | head -15'
            Description = @('Find all .conf files under /etc. Redirect stderr and limit to 15.')
            Hint = 'find /etc -name "*.conf" 2>/dev/null | head -15' }
        @{ Id = 15; Title = 'Check filesystem types'; Difficulty = 'advanced'
            ExpectedCommand = 'df -hT'
            Description = @('Use df -hT to show disk usage with filesystem type information.')
            Hint = 'df -hT' }
        @{ Id = 16; Title = 'Search AVC denials'; Difficulty = 'expert'
            ExpectedCommand = 'ausearch -m avc --start today 2>/dev/null'
            Description = @('Use ausearch to search for SELinux AVC denials from today.')
            Hint = 'ausearch -m avc --start today' }
        @{ Id = 17; Title = 'Check SELinux booleans'; Difficulty = 'expert'
            ExpectedCommand = 'cat /etc/selinux/config | grep -i selinux'
            Description = @('Read SELinux config and filter for SELinux settings lines.')
            Hint = 'cat /etc/selinux/config | grep -i selinux' }
        @{ Id = 18; Title = 'Backup home directory'; Difficulty = 'expert'
            ExpectedCommand = 'tar czf /tmp/home-student-backup.tar.gz -C /home student'
            Description = @('Create a compressed tar archive of /home/student in /tmp.')
            Hint = 'tar czf /tmp/backup.tar.gz -C /home student' }
        @{ Id = 19; Title = 'Review DNF history'; Difficulty = 'expert'
            ExpectedCommand = 'dnf history | head -15'
            Description = @('Use dnf history to review past package transactions.')
            Hint = 'dnf history | head -15' }
        @{ Id = 20; Title = 'Analyze log patterns'; Difficulty = 'expert'
            ExpectedCommand = 'grep -oP "CROND\[\d+\]" /var/log/messages | sort | uniq -c | sort -rn'
            Description = @('Extract CROND process IDs from messages, count occurrences, sort by frequency.')
            Hint = 'grep -oP "CROND\[\d+\]" /var/log/messages | sort | uniq -c | sort -rn' }
    )

    return @{ Filesystem = $fs; Tasks = $tasks }
}
