. "$PSScriptRoot/../engine/themes.ps1"
. "$PSScriptRoot/../engine/helpers.ps1"
. "$PSScriptRoot/../engine/core.ps1"

function Build-CYBERPUNKCOMMANDS {
    return @(
        C "whoami" @("ronin")
        C "hostname" @("netrunner")
        C "id" @("uid=0(root) gid=0(root) groups=0(root),4(adm),20(datacrawler)")
        C "icebreaker --scan arasaka.neonet/24" @("ICEbreaker v3.7.1 - Neural Interface Scanner",
            "------------------------------------------------",
            "Scanning subnet: arasaka.neonet/24",
            "Nodes discovered: 34",
            "",
            "  Host              ICE Level    Service              Port",
            "  ────────────────  ──────────  ───────────────────  ─────",
            "  10.0.1.1          ████ 4/5    Arasaka Firewall     22,80,443",
            "  10.0.1.14         ██ 2/5       Corp Data Server    8080",
            "  10.0.1.22         █████ 5/5    Black ICE Detected  4242",
            "  10.0.1.7          █ 1/5         Legacy Terminal     23",
            "",
            "⚠  1 Black ICE node detected. Evasion countermeasures active.")
        C "subnet-ping --burst arasaka.neonet" @("Pinging gateway: arasaka.neonet (10.0.1.1) ... OK (3ms)",
            "Pinging 10.0.1.2 ... OK (1ms) - Arasaka DNS",
            "Pinging 10.0.1.7 ... OK (12ms) - Legacy Term",
            "Pinging 10.0.1.14 ... OK (4ms) - Corp Data",
            "Pinging 10.0.1.22 ... TIMEOUT - Black ICE zone",
            "Pinging 10.0.1.30 ... OK (2ms) - Access Gateway",
            "Pinging 10.0.1.31 ... OK (3ms) - Mail Relay",
            "Pinging 10.0.1.42 ... OK (7ms) - Exec Terminal",
            "",
            "8 hosts alive / 1 timed out")
        Cprog "daemon-connect //data/corp/exec/finance_transfers" @("[DAEMON] //data/corp/exec/finance_transfers - connecting...",
            "[AUTH] Credentials required",
            "[AUTH] Using neural handshake...",
            "[AUTH] Biometric match: 98.7% - Access granted",
            "[DAEMON] Channel established at 2.4 Gbps",
            "",
            "  /finance_transfers/",
            "  ├── 2026-03-15_transactions.log  (4.2 MB)",
            "  ├── 2026-03-14_transactions.log  (3.8 MB)",
            "  ├── offscreen_accounts.csv        (1.1 MB)",
            "  └── .encrypted/",
            "      └── saka_project_delta.db    (encrypted)")
        C "blackice-detect --threshold 0.7 --range local" @("[BLACK ICE DETECTION ENGINE]",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "Scanning local node memory...",
            "Threshold: 0.7",
            "",
            "  Process                  Suspicion  ICE Signature",
            "  ───────────────────────  ─────────  ──────────────────────",
            "  system_daemon.exe        0.12       benign",
            "  neuro_link.sys           0.45       benign",
            "  data_parser.exe          0.89 ⚠    RABID-ICE v4.2",
            "  net_monitor.exe          0.23       benign",
            "  deck_bridge.sys          0.91 ⚠    DOPPELGANGER-ICE",
            "",
            "⚠ WARNING: 2 malicious ICE programs detected.",
            "⚠ Doppelganger ICE detected - memory corruption risk.")
        C "datamine --target //data/corp/exec/offscreen_accounts.csv --columns 'account,balance,owner'" @("[DATAMINE] Extracting from offscreen_accounts.csv",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "account          | balance        | owner",
            "───────────────── | ────────────── | ───────────────",
            "CH923048571      | $12,400,000.00 | Y. Tanaka",
            "CH923048572      | $8,200,000.00  | S. Arasaka",
            "CH923048573      | $22,000,000.00 | Shell Corp #4",
            "CH923048574      | $50,000.00     | M. Takashi",
            "CH923048575      | $45,800,000.00 | Shell Corp #7",
            "",
            "[OK] 5 records extracted to /data/exfil/accounts.json")
        C "net-monitor --all-interfaces" @("Interface         Status    RX pkt/s    TX pkt/s    Latency",
            "───────────────  ────────  ─────────  ─────────  ───────",
            "eth0             ACTIVE    2,345       1,892      3ms",
            "eth1             ACTIVE    12,450      14,200     7ms",
            "wlan0            ACTIVE    891         456        11ms",
            "loopback         ACTIVE    23,567      23,567     0ms",
            "",
            "Traffic analysis:",
            "  eth1 - high outbound activity to 10.0.1.1 (Arasaka FW)",
            "  eth0 - data exfil stream to secure tunnel")
        C "decrypt --algorithm xchacha20 --file data.exf" @("[DECRYPT] xchacha20 - data.exf",
            "Key: ******** (64-char hex key)",
            "Nonce: 2a4f71b9c83d5e0012345678",
            "",
            "[PROGRESS] ■■■■■■■■■■■■■■■■■■■■ 100%",
            "",
            "[OK] Decrypted 4.2 MB to data.exf.decrypted",
            "[OK] MIME type: application/sqlite3",
            "",
            "> file data.exf.decrypted",
            "data.exf.decrypted: SQLite 3.x database, page size 4096")
        C "trace-route 10.0.1.1" @("traceroute to 10.0.1.1 (10.0.1.1), 30 hops max, 60 byte packets",
            " 1  localhost.localnet (10.0.0.1)  0.345 ms  0.321 ms  0.298 ms",
            " 2  10.0.0.254 (10.0.0.254)  1.234 ms  1.198 ms  1.201 ms",
            " 3  arasaka-gw-01.arasaka.neonet (10.0.1.1)  3.456 ms  3.412 ms  3.398 ms",
            "",
            "Traceroute complete - 3 hops")
        C "access-log --show /var/log/icewall.log --tail 8" @("2026-03-16T04:12:01Z [AUTH] user=ronin action=login src=10.0.0.42 result=ALLOW",
            "2026-03-16T04:15:33Z [SCAN] probe=10.0.0.99 type=portscan target=10.0.1.1 result=BLOCK",
            "2026-03-16T04:20:12Z [AUTH] user=ytanaka action=login src=10.0.1.30 result=ALLOW",
            "2026-03-16T04:22:45Z [ICE] signature=RABID-ICE src=10.0.1.22 status=ACTIVE",
            "2026-03-16T04:30:01Z [AUTH] user=ronin action=data_request resource=finance_transfers result=ALLOW",
            "2026-03-16T04:31:22Z [EXFIL] data_out=2.4MB dest=10.0.0.42 channel=tunnel-enc status=COMPLETE",
            "2026-03-16T04:35:00Z [ICE] signature=DOPPELGANGER-ICE src=10.0.1.22 status=PROPAGATING",
            "2026-03-16T04:35:01Z [ALERT] ICE propagation detected - quarantine zone active")
        C "ls -la /data/exfil/" @("total 24576",
            "drwxrwxrwx 2 root datacrawler     4096 Mar 16 04:31 .",
            "drwxr-xr-x 5 root root            4096 Mar 14 22:00 ..",
            "-rw------- 1 root datacrawler  1204224 Mar 16 04:31 accounts.json",
            "-rw------- 1 root datacrawler  4194304 Mar 16 04:30 transfers.db",
            "-rw------- 1 root datacrawler  1048576 Mar 16 04:22 employee_emails.csv",
            "-rw------- 1 root datacrawler   524288 Mar 16 04:25 corp_structure.xml")
        C "ICE_status --verbose" @("ICE Status: ACTIVE",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Kernel ICE:       v4.2.1 (patched)",
            "  Black ICE Shield: ENABLED",
            "  Neural Firewall:  ACTIVE (latency 2ms)",
            "  Memory scrubber:  RUNNING",
            "",
            "  Active threats neutralized: 12",
            "  ICE profile changes: 3 (last 24h)",
            "  Last breach attempt: 2026-03-15 22:12:00",
            "  Breach count (session): 0")
        C "deck-config --show all" @("Cyberdeck Configuration",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Model:            DaisyChain III",
            "  Processor:        NeuroSync X9 @ 4.2 GHz",
            "  RAM:              64GB DDR6 Neural",
            "  Storage:          2TB Crystal NAND",
            "  ICE Suite:        ICEbreaker v3.7.1",
            "  Network:          Arasaka-Net bridge / DarkNet tor",
            "  Stealth Level:    0.94",
            "  Signal masking:   ENABLED (chameleon protocol)")
        C "cat /etc/netrunner/hosts" @("# Neural host file - Arasaka NET cluster",
            "127.0.0.1       localhost localhost.neural",
            "10.0.1.1        gateway.arasaka.neonet gw",
            "10.0.1.14       dataserv.corp dataserv",
            "10.0.1.22       blackice-zone.arasaka.neonet DANGER",
            "10.0.1.30       exec-terminal arasaka-exec",
            "10.0.0.254      edge-router edge",
            "10.0.0.42       netrunner netrunner.local",
            "# Tunnel endpoints",
            "203.0.113.1     darknet-relay darknet")
    )
}

if ($MyInvocation.InvocationName -ne '.') {
    Start-TerminalSession -CommandBuilder ${function:Build-CYBERPUNKCOMMANDS} -Theme (Get-Theme cyberpunk) -ModeName "Cyberpunk" -TargetHost "netrunner" -TargetDomain "arasaka.neonet" -TargetIP (RandIP) -TargetCompany "Arasaka Corporation" -TargetLocation "Night City" -TargetOS "NET-OS 4.7" -OSPrompt "ronin@netrunner:~$ " -AllowFailures
}