. "$PSScriptRoot/../engine/themes.ps1"
. "$PSScriptRoot/../engine/helpers.ps1"
. "$PSScriptRoot/../engine/core.ps1"

function Build-MATRIXCOMMANDS {
    return @(
        C "whoami" @("neo")
        C "hostname" @("matrix")
        C "id" @("uid=0(root) gid=0(root) groups=0(root),1(operator),2(program)")
        C "trace --program 'KeyMaker.exe'" @("[TRACE] Resolving program: KeyMaker.exe",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Signature:    0x7A3F B12C 9D4E 8F01",
            "  Construct:    KeyMaker v2.4.1 (Matrix native)",
            "  Location:     /sys/core/programs/KeyMaker.exe",
            "  Access Level: ADMIN",
            "  Lock Status:  ACTIVE",
            "",
            "  Call chain:",
            "    ├── → main() @ 0x401000",
            "    ├── → validate_key() @ 0x405A24",
            "    └── → grant_access() @ 0x4081B0",
            "",
            "  [OK] Program traced. Ready to construct.")
        C "locate --exit '01:00:00:00:00:01'" @("[LOCATE] Searching for exit pattern: 01:00:00:00:00:01",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Scanning construct layers...",
            "  Layer 1: Residential zone — phone booths: 4",
            "  Layer 2: Office zone — hardlines: 12",
            "  Layer 3: Government zone — restricted: 2",
            "  Layer 4: Core zone — exits: 1",
            "",
            "  Closest exit:",
            "    > 1514 H Street NW, Washington DC",
            "    > Phone: (202) 555-0142",
            "    > Status: ACTIVE (not guarded)")
        Cprog "sentinel-scan --range 100m" @("[SENTINEL] Active scan — 100m radius",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Scanning constructs...",
            "  ████████████████████████████████████████ 100%",
            "",
            "  Entity          Type         Status     Threat",
            "  ─────────────── ──────────── ────────── ──────",
            "  Agent Smith     Agent         TRACKED   HIGH",
            "  Agent Brown     Agent         TRACKED   HIGH",
            "  Agent Jones     Agent         TRACKED   HIGH",
            "  Civilian #442   Bluepill      IGNORE    —",
            "  Civilian #891   Bluepill      IGNORE    —",
            "  Switch          Operative     ALLY      LOW",
            "  Morpheus        Operative     ALLY      LOW",
            "",
            "  ⚠ 3 Agents within 100m. Evacuation recommended.")
        C "agent-detect --probability" @("[AGENT DETECTION] Probability analysis",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Current environment density: 234 entities",
            "  Agent probability: 9.2%",
            "  Agent signatures matched: 3",
            "  Signature confidence: 87.3%",
            "",
            "  Profile: Agent Smith (confirmed)",
            "  ─────────────────────────────",
            "  Last seen: 60s ago (west wing, level 3)",
            "  Behavior: predictive pattern — sweeping grid",
            "  Estimated intercept: 4 min 22 sec",
            "",
            "  Recommendation: move to hardline point alpha")
        C "hack --target 'MatrixMainframe' --method construct" @("[HACK] Engaging MatrixMainframe...",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Target:       MatrixMainframe /sys/core",
            "  Method:       Construct injection",
            "  Authorization: KeyMaker construct loaded",
            "",
            "  ████████████████████████░░░░░░ 78%",
            "  Injecting payload... OK",
            "  Bypassing ICE wall... OK",
            "  Gaining root access... OK",
            "",
            "  [ACCESS GRANTED]",
            "  You are connected to the Matrix mainframe.",
            "  Tip: 'construct-load' to load assets.")
        C "construct-load 'database/weapons.xml'" @("[CONSTRUCT] Loading: database/weapons.xml",
            "  Construct size: 2.4 MB",
            "  Compatibility: ZionOS 2.1 ✅",
            "",
            "  Weapons database loaded:",
            "  ├── Sidearm:    M9 Beretta (standard issue)",
            "  ├── Rifle:      H&K G36C (tactical)",
            "  ├── Heavy:      M249 SAW (suppressive)",
            "  ├── Special:    EMP Grenade (anti-agent)",
            "  └── Custom:     Mark III Gauntlet (Morpheus)",
            "",
            "  [OK] 47 weapon profiles cached to memory.")
        C "jump --gateway '01:00:00:00:00:42'" @("[JUMP] Initiating gate jump...",
            "  Gateway: 01:00:00:00:00:42",
            "  Destination: Zion mainframe relay",
            "  Bandwidth: 1.2 Tbps",
            "",
            "  ████████████████████████████████████████ 100%",
            "",
            "  Connection established.",
            "  Latency: 4ms | Signal: 97.2%",
            "  Welcome back to Zion, Neo.")
        C "reality-check --stability 92.7" @("[REALITY CHECK] Stability assessment",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Measured stability: 92.7%",
            "  Baseline: 89.4%",
            "  Deviation: +3.3% (within tolerance)",
            "",
            "  Construct integrity: ██████████░░ 92.7%",
            "  Glitch probability:  0.003%",
            "  Anomaly count:       0 (clean)",
            "",
            "  Status: STABLE — no construct degradation detected.")
        C "code-read --file /etc/matrix/config.ini" @("[CODE READ] /etc/matrix/config.ini",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "[construct]",
            "  version = 6.2.1",
            "  stability_threshold = 0.85",
            "  auto_stabilize = true",
            "",
            "[agents]",
            "  behavior_model = predictive_v4",
            "  patrol_pattern = grid",
            "  alert_on_anomaly = true",
            "  response_time_ms = 500",
            "",
            "[exits]",
            "  default_count = 42",
            "  phone_booth_model = vintage",
            "  hardline_count = 16",
            "",
            "[zion]",
            "  connection_pool = 8",
            "  encryption = post_quantum",
            "  relay_primary = zion-relay-01.matrix")
        C "cat /proc/version" @("Matrix construct version 6.2.1 (post-human)",
            "Simulation core v4.7.2 (c) 2199 Human Engineering Project",
            "Built on Mar 14 2199 09:22:01 UTC",
            "ZionOS compatibility layer: v2.1",
            "Architecture: simulated x86_64")
        C "phreak --line '555-FICTION'" @("[PHREAK] Targeting phone line: 555-FICTION",
            "  Switch type: Lucent 5ESS (digital)",
            "  Route: PSTN → Matrix bridge → hardline",
            "",
            "  ████████████████████████████████████████ 100%",
            "",
            "  Line accessed. Routes available:",
            "  1. Zion Control (secure)",
            "  2. Nebuchadnezzar (internal)",
            "  3. Matrix relay node 4 (tapped)",
            "  4. Exit: Washington DC hardline",
            "",
            "  Select route: _")
        C "broadcast --message 'Neo is the One' --channel operator" @("[BROADCAST] Channel: operator",
            "  Message: 'Neo is the One'",
            "  Encoding: neural pulse (encrypted)",
            "  Recipients: Morpheus, Trinity, Switch, Tank, Dozer",
            "",
            "  ████████████████████████████████████████ 100%",
            "",
            "  [OK] Message delivered. Acknowledgment from 4 recipients.",
            "  Trinity: 'I know.'")
        C "trace-exit --quick" @("[EXIT TRACE] Scanning for nearest safe exit...",
            "  ████████████████████████████████████████ 100%",
            "",
            "  Nearest exit: HARD-07 (subway tunnel level 4)",
            "  Distance: 220m",
            "  Route: clear of agents",
            "  Phone booth: ACTIVE",
            "",
            "  Estimated time to exit: 3 min 12 sec",
            "  Recommended action: MOVE NOW")
    )
}

if ($MyInvocation.InvocationName -ne '.') {
    Start-TerminalSession -CommandBuilder ${function:Build-MATRIXCOMMANDS} -Theme (Get-Theme matrix) -ModeName "Matrix" -TargetHost "neo" -TargetDomain "matrix" -TargetIP (RandIP) -TargetCompany "Zion" -TargetLocation "Nebuchadnezzar" -TargetOS "ZionOS 2.1" -OSPrompt "neo@matrix:~$ " -AllowFailures
}