. "$PSScriptRoot/../engine/themes.ps1"
. "$PSScriptRoot/../engine/helpers.ps1"
. "$PSScriptRoot/../engine/core.ps1"

function Build-MRROBOTCOMMANDS {
    return @(
        C "whoami" @("root")
        C "hostname" @("fsociety")
        C "id" @("uid=0(root) gid=0(root) groups=0(root)")
        C "cat /etc/fsociety/members.txt" @("=== fsociety Members ===",
            "",
            "mrrobot            — Elliot Alderson",
            "darlene            — Darlene Alderson",
            "cisco              — Cisco",
            "romero             — Romero",
            "mobley             — Mobley",
            "trenton            — Trenton",
            "whiterose          — Whiterose (Minister Zhang)",
            "tyrell             — Tyrell Wellick (ally)")
        Cprog "ddos --target 'https://www.e-corp.com' --workers 500 --duration 120" @("[DDOS] Initializing distributed denial of service...",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Target:  https://www.e-corp.com",
            "  Workers: 500",
            "  Duration: 120s",
            "  Method:  HTTP flood + SYN flood",
            "",
            "  Workers deployed across 12 nodes",
            "  ████████████████████████████████████████ 100%",
            "",
            "  Rate:     45,321 req/s",
            "  Success:  5,438,521 packets sent",
            "  Errors:   12 (0.0002%)",
            "  Target status: TIMEOUT (no response)",
            "  [OK] e-corp.com is DOWN.")
        C "wipe --disk /dev/sda --method dod --passes 3" @("[WIPE] Disk sanitization — /dev/sda",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "  Method: DoD 5220.22-M (3-pass)",
            "  Pass 1:  0x00 write — ██████████████████████ 100%",
            "  Pass 2:  0xFF write — ██████████████████████ 100%",
            "  Pass 3:  random data — ██████████████████████ 100%",
            "  Verification: ██████████████████████ 100%",
            "",
            "  [COMPLETE] 500GB sanitized.",
            "  WARNING: This disk is now blank.")
        Cprog "encrypt --path /mnt/e-corp/data --key fsociety_key.pub" @("[ENCRYPT] Batch encryption — /mnt/e-corp/data",
            "  Algorithm: RSA-4096 + AES-256-GCM",
            "  Key: fsociety_key.pub",
            "  Files found: 1,247",
            "",
            "  ██████████████████████░░░░░░░░░░░░░░ 55%",
            "  Encrypted: 689 / 1247 files",
            "  Running total: 2.4 GB encrypted",
            "",
            "  Ransom note: /mnt/e-corp/FSOCIETY_README.txt written.",
            "  Message: 'E Corp owes $5.2M in赎金. Pay or data burns.'")
        C "social-eng --target 'tyrell@e-corp.com' --template phishing_urgent.txt" @("[SOCIAL ENGINEERING] Crafting attack",
            "  Target:    tyrell@e-corp.com",
            "  Template:  phishing_urgent.txt",
            "  Vector:    email spoof (executive@e-corp-internal.com)",
            "",
            "  Subject:   URGENT: Wire transfer approval needed EOD",
            "  Body:      Tyrell, the board needs your approval on the",
            "             Q4 acquisition wire. Sign here: [LINK]",
            "",
            "  [SENT] 2026-03-16 05:12:00 UTC",
            "  [OPENED] 2026-03-16 05:14:23 UTC",
            "  [LINK CLICKED] 2026-03-16 05:14:31 UTC",
            "  [CREDENTIALS CAPTURED] tyrell / I_Love_My_Son!23")
        C "scan --target 10.0.0.0/24 --verbose" @("Target: 10.0.0.0/24 — E Corp internal subnet",
            "  Hosts discovered: 15",
            "",
            "  10.0.0.1    UP     Gateway",
            "  10.0.0.5    UP     DNS server",
            "  10.0.0.10   UP     Mail server (exchange.e-corp.com)",
            "  10.0.0.15   UP     File server (files.e-corp.com)",
            "  10.0.0.20   UP     Web server (www.e-corp.com)",
            "  10.0.0.50   UP     Database server (db.e-corp.com)",
            "  10.0.0.100  UP     Tyrell's workstation (TYRELL-PC)",
            "  10.0.0.254  UP     Domain controller (DC-01.e-corp.com)",
            "",
            "  Vulnerable services found: 7",
            "  Recommendations: focus on DC-01 (SMB)")
        C "curl -s http://www.e-corp.com/robots.txt" @("User-agent: *",
            "Disallow: /admin",
            "Disallow: /internal",
            "Disallow: /backup",
            "Disallow: /finance",
            "Disallow: /secret/",
            "# fsociety was here — Oct 12, 2015")
        Cprog "sqlmap -u 'https://admin.e-corp.com/login' --dbs --batch" @("        ___",
            "       __H__",
            " ___ ___[(]_____ ___ ___  {1.8.2#stable}",
            "|_ -| . [']     | .'| . |",
            "|___|_  [(]_|_|_|__,|  _|",
            "      |_|V...       |_|   https://sqlmap.org",
            "",
            "[05:22:01] [INFO] testing 'Generic UNION query (NULL) - 1 to 20 columns'",
            "[05:22:04] [INFO] target URL appears to be injectable",
            "[05:22:08] [INFO] fetching database names",
            "available databases [6]:",
            "[*] e_corp_main",
            "[*] e_corp_finance",
            "[*] e_corp_hr",
            "[*] e_corp_payroll",
            "[*] e_corp_secret",
            "[*] information_schema")
        C "openssl enc -aes-256-cbc -salt -in victims.txt -out victims.enc" @("[ENCRYPT] Using OpenSSL AES-256-CBC",
            "  Input:   victims.txt (2.4 MB)",
            "  Output:  victims.enc",
            "  Salt:    generated (8 bytes)",
            "  Key:     derived from passphrase (scrypt)",
            "",
            "  [OK] File encrypted.",
            "  WARNING: Original file victims.txt NOT shredded.")
        C "whois e-corp.com" @("   Domain Name: E-CORP.COM",
            "   Registry Domain ID: 123456789_DOMAIN_COM-VRSN",
            "   Registrar: MarkMonitor Inc.",
            "   Registrar IANA ID: 292",
            "   Registrar Abuse Contact Email: abuse@markmonitor.com",
            "   Registrar Abuse Contact Phone: +1.2083895740",
            "   Domain Status: clientDeleteProhibited",
            "   Domain Status: clientTransferProhibited",
            "   Name Server: NS1.E-CORP.COM",
            "   Name Server: NS2.E-CORP.COM",
            "   Creation Date: 1998-04-15T04:00:00Z",
            "   Expiration Date: 2026-04-15T04:00:00Z",
            "   Registrant Organization: E Corp Holdings Ltd.")
        C "dig e-corp.com ANY" @("; <<>> DiG 9.18.24 <<>> e-corp.com ANY",
            ";; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4321",
            ";; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1",
            "",
            "e-corp.com.             300     IN      A       198.51.100.20",
            "e-corp.com.             300     IN      AAAA    2001:db8::20",
            "e-corp.com.             300     IN      MX      10 mail.e-corp.com.",
            "e-corp.com.             300     IN      TXT     ""v=spf1 include:_spf.e-corp.com ~all""",
            "e-corp.com.             300     IN      NS      ns1.e-corp.com.",
            "e-corp.com.             300     IN      NS      ns2.e-corp.com.",
            "",
            ";; Query time: 47 msec",
            ";; SERVER: 8.8.8.8#53(8.8.8.8)")
        C "head -20 /var/log/e-corp/access.log" @("192.168.1.10 - - [16/Mar/2026:05:00:01 +0000] ""GET / HTTP/1.1"" 200 5432",
            "192.168.1.10 - - [16/Mar/2026:05:00:02 +0000] ""GET /css/main.css HTTP/1.1"" 304 0",
            "192.168.1.15 - - [16/Mar/2026:05:01:12 +0000] ""POST /login HTTP/1.1"" 302 0",
            "192.168.1.15 - - [16/Mar/2026:05:01:13 +0000] ""GET /dashboard HTTP/1.1"" 200 12450",
            "10.0.0.50 - - [16/Mar/2026:05:02:00 +0000] ""GET /admin/backup HTTP/1.1"" 403 42",
            "10.0.0.50 - - [16/Mar/2026:05:02:01 +0000] ""POST /admin/backup HTTP/1.1"" 200 89",
            "127.0.0.1 - - [16/Mar/2026:05:05:00 +0000] ""GET /status HTTP/1.1"" 200 12",
            "[...]  fsociety access_log modified: 2026-03-16 05:15:00")
        C "fsociety-banner" @("        _____________________________",
            "       |  _________________________  |",
            "       | |                         | |",
            "       | |  F   S   O   C   I   E  | |",
            "       | |    T      Y             | |",
            "       | |_________________________| |",
            "       |_____________________________|",
            "              \\_______________/",
            "               ###############",
            "",
             "     `"Hello, friend.`" - Elliot Alderson",
            "",
            "  fsociety has infiltrated E Corp systems.",
            "  5,438,521 packets sent to target.",
            "  Data encrypted: 2.4 GB.",
            "  Accounts compromised: 17.",
            "",
            "  [STATUS] Operation completed. Awaiting next command.")
    )
}

if ($MyInvocation.InvocationName -ne '.') {
    Start-TerminalSession -CommandBuilder ${function:Build-MRROBOTCOMMANDS} -Theme (Get-Theme mrrobot) -ModeName "Mr. Robot" -TargetHost "fsociety" -TargetDomain "evil-corp" -TargetIP (RandIP) -TargetCompany "E Corp" -TargetLocation "New York" -TargetOS "Kali Linux 2024.1" -OSPrompt "root@fsociety:~#" -AllowFailures
}